### ISSUE TITLE
how to find the url about the first live broadcast of olive.c,

### ISSUE THREAD

**Issue by wenchaomartin** [tsoding/olive.c#15]
This is not a bug, I just want to ask for help, I want to learn the first live broadcast of olive.c, but I can't find the video of the first episode now, maybe the live broadcast video has expired. Can you again provide a first live video about olive.c? Now the first episode of Olive Live is lol

**Comment by ferasboulala** [comment]
https://www.youtube.com/watch?v=LmQKZmQh1ZQ&ab_channel=TsodingDaily

**Comment by wenchaomartin** [comment]
thanks
